### ISSUE TITLE
API Addition: Add modifier for start and finish fields in Maze

### ISSUE THREAD

**Issue by drew-beckmen** [Pingry-Java/MazeSolver#11]

**Comment by msun2019** [comment]
k

**Comment by msun2019** [comment]
permission granted william you are clear for take off

**Comment by jorndorff** [comment]
Doesn't this allow anyone to "Solve" a maze by changing its finish Node to be the same as its start Node?

**Comment by drew-beckmen** [comment]
Use protected keyword to prevent user interaction with those methods
