### ISSUE TITLE
Issue in SampleMaze

### ISSUE THREAD

**Issue by tdrizzlewizard** [Pingry-Java/MazeSolver#17]
public class SampleMaze extends Maze
       ^
./SampleMaze.java:9: error: constructor MazeSquare in class MazeSquare cannot be applied to given types;
		super(new MazeSquare(1, 0, 1), new MazeSquare(2, 3, 1)); 
		      ^
  required: int,int,int,boolean
  found: int,int,int

**Comment by drew-beckmen** [comment]
fixed
