### ISSUE TITLE
MazeSolver.class committed

### ISSUE THREAD

**Issue by jorndorff** [Pingry-Java/MazeSolver#2]
The repo is for code and documentation only. It should not include bytecode files which is why they're in the `.gitignore`

**Comment by jorndorff** [comment]
I fixed this in commit 48c00cb22284c8ce6c4cd1f8450bdbd3f7fdd05e

**Comment by jorndorff** [comment]
JK, I didn't really fix it that was an example

**Comment by mbergam2019** [comment]
I fixed this with 34b5fa6260da15da34344029b28f4234ff1c49ac
