### ISSUE TITLE
Compilation warning in the Gui file

### ISSUE THREAD

**Issue by mpavlak2018** [Pingry-Java/MazeSolver#21]
When compiling the work I did on the saving feature, I got a "unchecked or unsafe operations" warning, and was told to recompile with -Xlint:unchecked for more details. However, when I compiled with -Xlint:unchecked it didn't give me any more details. I'm not sure if this is a warning we can/should work on fixing, but I wanted to see if anyone has any thoughts on it/what likely caused it.

**Comment by jorndorff** [comment]
I want to help with this, but I need steps to reproduce it. What branch are you on? What file are you compiling?

**Comment by mpavlak2018** [comment]
Master (I merged what I had been working on in manually as we discussed), this happens when compiling MazeGui (running the gui files). It only showed the warning on the first try for me. I tried doing -Xlint:unchecked, but I couldn't get the more detailed warning message. I looked it up a bit/messed around with it, and I found that -Xlint:all actually gave me more details: `$ javac -Xlint:all MazeGui.java 
./Maze.java:4: warning: [serial] serializable class Maze has no definition of serialVersionUID
public abstract class Maze implements Serializable, Checkpointable {
                ^
./generateMaze.java:6: warning: [serial] serializable class generateMaze has no definition of serialVersionUID
public class generateMaze extends Maze
       ^
./GuiFrame.java:23: warning: [unchecked] unchecked cast
			mazeList = (ArrayList<Maze>)objectIn.readObject();
			                                               ^
  required: ArrayList<Maze>
  found:    Object
./GuiFrame.java:11: warning: [serial] serializable class GuiFrame has no definition of serialVersionUID
public class GuiFrame extends JFrame {
       ^
4 warnings ` The sample code I looked at for serializable didn't do anything other than add implements serializable (I actually thought this was weird at the time as well), so I'm going to do some research to figure out what the serialVersionUID is. Also, any ideas for dealing with the unchecked cast well?

**Comment by jorndorff** [comment]
Just an FYI, you can bring the warning back by deleting `GuiFrame.class` then recompiling.

Update:
If you do that, then compile with `-Xlint:unchecked` you can get the details. The detailed version of this particular warning are included in what you pasted above, but here it is on its own:

```
./GuiFrame.java:23: warning: [unchecked] unchecked cast
             mazeList = (ArrayList<Maze>)objectIn.readObject();
                                                             ^
  required: ArrayList<Maze>
  found: Object
1 warning
```

**Comment by jorndorff** [comment]
I think https://stackoverflow.com/a/16929559/4184410 might solve this.

**Comment by mpavlak2018** [comment]
Can we get some other people to check to see if the warnings are gone before we close this?

**Comment by jorndorff** [comment]
Looks like it's gone to me.
