### ISSUE TITLE
Implementation of getNeighbors

### ISSUE THREAD

**Issue by lindseyyu** [Pingry-Java/MazeSolver#3]
(I) In what order does getNeighbors return the Nodes (up, right, down, left + diagonals?) 

(II) It might be eaiser to move the method to the Maze class like this:
      public Node getNeighbors(Node current);  

Just a suggestion.

**Comment by drew-beckmen** [comment]
This API change is ok.

**Comment by msun2019** [comment]
GUI people are ok w/ this

**Comment by drew-beckmen** [comment]
This is fixed.
