### ISSUE TITLE
Consolidate Node classes?

### ISSUE THREAD

**Issue by jorndorff** [Pingry-Java/MazeSolver#9]
Looks like no one has used the `Wall` class or any `Node`s other than `Maze Square`. Let's decide to do exactly one of the following.

1. Start abstracting details of various types of Nodes into proper subclasses
2. Change the API so Node is a concrete class (probably implemented as `MazeSquare` currently is) and remove the `Wall` and `MazeSquare` classes.

**Comment by drew-beckmen** [comment]
We will get rid of the Wall class

**Comment by jorndorff** [comment]
So what's the final status here? In what commit was `Node` removed? Any reason this is still open?

**Comment by drew-beckmen** [comment]
Wall has been removed. We are keeping abstract class Node.
